version: 0.0
os: linux
files:
  - source: html/index.html
    destination: /var/www/html
  - source: /html/images
    destination: /var/www/html/images
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

# DownloadBundle:

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

# Install:
# AfterInstall:

  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
      
# ValidateService:
